            - name: Tenant provisioning -0123
  uses: atlassian/gajira-create@v3
  with:
    # Key of the project
    project: 
    wM CloudOps (CSOWAS)
    issuetype: 
    Ticket
    summary: 
    Tenant provisioning automation
    description: PR raised to provision the tenant
    fields: # optional
          
